= {product-title} {product-version} Documentation
{product-author}
{product-version}
:data-uri:
:icons:

Welcome to RedBridge Apps documentation. Here you will find information and resources to help you learn about RedBridge Apps and its features. From getting started with creating your first application to using the advanced features.

RedBridge Apps is powered by link:http://www.openshift.org/[*OpenShift Origin*]


[cols="2",frame="none",grid="cols"]
|===


a|link:../getting_started/overview.html[*Getting Started*]

Describes the initial steps required to begin using RedBridge Apps and create your first application.

a|link:../client_tools_install_guide/overview.html[*Installing client Tools*]

These topics describe how to install and configure the RedBridge Apps command line interface (CLI) client tools on various operating systems and prepare your workstation to communicate with the remote server.

a|link:../user_guide/overview.html[*User Guide*]

Describes key concepts of OpenShift with instructions on how to use the features to create and manage RedBridge Apps applications.

a|link:../cartridge_specification_guide/overview.html[*Developing Cartridges*]

These topics provide reference information and specifications for developing custom cartridges for RedBridge Apps.
|===

